import { Country } from '@/types';

export const COUNTRIES: Country[] = [
  // ── Tier 1 ─────────────────────────────────────────────────────────────────
  {
    id: 'jp',
    nameZh: '日本',
    nameEn: 'Japan',
    flag: '🇯🇵',
    tier: 1,
    region: '东亚',
    gdp: '4.23万亿',
    population: '1.24亿',
    gdpPerCapita: '3.4万',
    mainIndustries: ['汉方制剂', '功能性表示食品', '药妆品', '医疗器械'],
    summary: '全球第三大健康产品市场，汉方文化根深蒂固，Tsundra年销售额超1200亿日元',
    description: '日本是全球最成熟的汉方健康产品市场，汉方药市场规模约1,800亿日元，功能性表示食品市场约7,000亿日元。中国药食同源原料在日本消费者中有高度认知，是最快切入路径。',
    opportunityCount: 42,
    color: '#e74c3c',
  },
  {
    id: 'kr',
    nameZh: '韩国',
    nameEn: 'South Korea',
    flag: '🇰🇷',
    tier: 1,
    region: '东亚',
    gdp: '1.66万亿',
    population: '5200万',
    gdpPerCapita: '3.2万',
    mainIndustries: ['韩方/汉药', '化妆品', '功能性食品', '医疗器械'],
    summary: '韩方市场规模约25亿美元，功能性食品制度完善，国内原料九成依赖进口',
    description: '韩国韩方（K-汉方）市场成熟，韩国人为导入中国中草药原料的最大市场之一。K-Beauty和K-Food的全球风靡带动了功能性食品出口，中国企业可作为原料供应商或ODM/OEM合作切入。',
    opportunityCount: 31,
    color: '#3498db',
  },
  {
    id: 'sg',
    nameZh: '新加坡',
    nameEn: 'Singapore',
    flag: '🇸🇬',
    tier: 1,
    region: '东南亚',
    gdp: '4668亿',
    population: '604万',
    gdpPerCapita: '7.7万',
    mainIndustries: ['中药', '保健品', '中医诊所', '医疗旅游'],
    summary: '东南亚中医药枢纽，华人占比76%，中医合法化程度最高的东南亚国家',
    description: '新加坡中医合法化程度高，中医师须在新加坡中医管理委员会注册，华人社区对中医药接受度极高。是进入东南亚市场的最佳跳板，也是中医药国际形象最佳的市场之一。',
    opportunityCount: 18,
    color: '#e74c3c',
  },
  {
    id: 'vn',
    nameZh: '越南',
    nameEn: 'Vietnam',
    flag: '🇻🇳',
    tier: 1,
    region: '东南亚',
    gdp: '4334亿',
    population: '1亿',
    gdpPerCapita: '4300',
    mainIndustries: ['中药材', '保健品', '传统医药', '食品饮料'],
    summary: '年均GDP增速6-7%，华人商圈强大，河内-胡志明双核市场，渠道进入最佳时机',
    description: '越南经济快速增长，华人商圈历史悠久，对中医药接受度较高。越南中医药监管相对宽松，是中国中医药企业出海东南亚成本最低、回报最快的市场之一。',
    opportunityCount: 24,
    color: '#f39c12',
  },
  // ── Tier 2 ─────────────────────────────────────────────────────────────────
  {
    id: 'my',
    nameZh: '马来西亚',
    nameEn: 'Malaysia',
    flag: '🇲🇾',
    tier: 2,
    region: '东南亚',
    gdp: '4070亿',
    population: '3430万',
    gdpPerCapita: '1.2万',
    mainIndustries: ['中药', '燕窝/保健品', '清真认证产品', '电商'],
    summary: '东南亚最大中医药市场，华人占23%，中医药历史最深，清真认证是独特机会',
    description: '马来西亚是东南亚中医药最成熟市场，政府认可中医，马来西亚华人占总人口23%对中医药需求旺盛。清真认证（Halal）是独特壁垒，合规产品可借此进入全球伊斯兰市场。',
    opportunityCount: 22,
    color: '#f1c40f',
  },
  {
    id: 'id',
    nameZh: '印度尼西亚',
    nameEn: 'Indonesia',
    flag: '🇮🇩',
    tier: 2,
    region: '东南亚',
    gdp: '1.37万亿',
    population: '2.78亿',
    gdpPerCapita: '4900',
    mainIndustries: ['传统医药', '保健品', '医疗器械', '食品饮料'],
    summary: '东南亚最大市场，人口红利巨大，中医药认知度高但合规体系尚在建设中',
    description: '印尼人口世界第四，2.78亿人口提供巨大市场容量。中医药在当地华人圈和主流社会均有认知，BPOM（食品药品监督局）是主要监管机构。渠道以传统药材铺和药房为主。',
    opportunityCount: 19,
    color: '#27ae60',
  },
  {
    id: 'th',
    nameZh: '泰国',
    nameEn: 'Thailand',
    flag: '🇹🇭',
    tier: 2,
    region: '东南亚',
    gdp: '5740亿',
    population: '7180万',
    gdpPerCapita: '8000',
    mainIndustries: ['泰中药', '保健品', 'SPA产品', '医疗旅游'],
    summary: '泰中药有独特的本土化传统，与中国中医药有融合空间，政府积极推动医疗旅游',
    description: '泰国传统医学（泰中药）与中医药有深厚渊源，两者在药材使用和理论上高度重叠。泰国食品药品监督管理局（TFDA）是主要监管机构，产品注册相对高效，医疗旅游市场发达。',
    opportunityCount: 17,
    color: '#e67e22',
  },
  {
    id: 'ph',
    nameZh: '菲律宾',
    nameEn: 'Philippines',
    flag: '🇵🇭',
    tier: 2,
    region: '东南亚',
    gdp: '4040亿',
    population: '1.15亿',
    gdpPerCapita: '3500',
    mainIndustries: ['保健品', '中药材', '医疗器械', '食品饮料'],
    summary: '华人商圈活跃，FDA监管较宽松，是进入东盟市场的低成本练手市场',
    description: '菲律宾华人约占总人口2%，华人商圈经济实力强，对中医药接受度高。菲律宾FDA监管相对宽松，食品和保健品进入门槛低于其他东盟国家，适合作为出海初期的练手市场。',
    opportunityCount: 14,
    color: '#3498db',
  },
  // ── Tier 3 ─────────────────────────────────────────────────────────────────
  {
    id: 'in',
    nameZh: '印度',
    nameEn: 'India',
    flag: '🇮🇳',
    tier: 3,
    region: '南亚',
    gdp: '3.73万亿',
    population: '14.4亿',
    gdpPerCapita: '2600',
    mainIndustries: ['传统医药(Ayurveda)', '原料药', '保健品', '医疗器械'],
    summary: '全球最大仿制药出口国，阿育吠陀体系成熟，植物药市场约30亿美元',
    description: '印度Ayurveda（阿育吠陀）体系与中国中医药有诸多相似之处，中国中药材可作为原料进入印度市场。印度制药业全球领先，对高质量原料药需求旺盛，是API出口的重要目标市场。',
    opportunityCount: 11,
    color: '#e67e22',
  },
  {
    id: 'lk',
    nameZh: '斯里兰卡',
    nameEn: 'Sri Lanka',
    flag: '🇱🇰',
    tier: 3,
    region: '南亚',
    gdp: '840亿',
    population: '2200万',
    gdpPerCapita: '3800',
    mainIndustries: ['传统医药', '香料出口', '保健品', '茶叶'],
    summary: '传统医学体系成熟，对中药材有认知，EDB提供出口促进支持',
    description: '斯里兰卡拥有独特的传统医学体系，对中药材有一定认知和需求。斯里兰卡出口发展局（EDB）提供贸易促进服务，是进入南亚市场的便捷通道。',
    opportunityCount: 8,
    color: '#8e44ad',
  },
  {
    id: 'np',
    nameZh: '尼泊尔',
    nameEn: 'Nepal',
    flag: '🇳🇵',
    tier: 3,
    region: '南亚',
    gdp: '360亿',
    population: '3100万',
    gdpPerCapita: '1200',
    mainIndustries: ['传统医药', '草药', '农产品', '手工业'],
    summary: '传统医学与中医药高度融合，喜马拉雅草药资源丰富，渠道成本极低',
    description: '尼泊尔传统医学与中医药高度融合，对中医药接受度极高。喜马拉雅地区草药资源丰富，中国中医药企业可通过合作、合资方式进入当地市场，渠道建设成本低。',
    opportunityCount: 6,
    color: '#c0392b',
  },
  {
    id: 'pk',
    nameZh: '巴基斯坦',
    nameEn: 'Pakistan',
    flag: '🇵🇰',
    tier: 3,
    region: '南亚',
    gdp: '3740亿',
    population: '2.4亿',
    gdpPerCapita: '1600',
    mainIndustries: ['传统医药(Unani)', '原料药', '医疗器械', '食品饮料'],
    summary: 'Unani传统医学体系，与中医药有对话基础，2.4亿人口提供广阔市场',
    description: '巴基斯坦Unani传统医学体系与中国中医药有理论层面的对话基础，对天然药物接受度高。巴基斯坦2.4亿人口提供广阔市场，DRAP（药品监管局）是主要监管机构。',
    opportunityCount: 7,
    color: '#27ae60',
  },
  {
    id: 'la',
    nameZh: '老挝',
    nameEn: 'Laos',
    flag: '🇱🇦',
    tier: 3,
    region: '东南亚',
    gdp: '157亿',
    population: '740万',
    gdpPerCapita: '2100',
    mainIndustries: ['传统医药', '草药', '食品', '贸易'],
    summary: '中国-老挝铁路开通带来历史性机遇，万象-磨丁经济走廊是核心增长极',
    description: '中老铁路2021年开通，万象-磨丁经济走廊成为中国-东南亚陆路贸易的核心节点。老挝传统医学与中国中医药有文化交流基础，渠道建设成本低，是进入东南亚市场的独特切入点。',
    opportunityCount: 5,
    color: '#c0392b',
  },
  {
    id: 'kh',
    nameZh: '柬埔寨',
    nameEn: 'Cambodia',
    flag: '🇰🇭',
    tier: 3,
    region: '东南亚',
    gdp: '330亿',
    population: '1700万',
    gdpPerCapita: '1900',
    mainIndustries: ['传统医药', '食品', '保健品', '贸易'],
    summary: '华人商圈活跃，渠道进入门槛低，可作为东南亚市场前哨基地',
    description: '柬埔寨华人商圈历史悠久，对中医药认知和接受度高。柬埔寨华人约占总人口5%，经济实力强。中国-柬埔寨双边贸易关系良好，是进入东南亚市场的低成本前哨基地。',
    opportunityCount: 5,
    color: '#8e44ad',
  },
  {
    id: 'mm',
    nameZh: '缅甸',
    nameEn: 'Myanmar',
    flag: '🇲🇲',
    tier: 3,
    region: '东南亚',
    gdp: '690亿',
    population: '5400万',
    gdpPerCapita: '1300',
    mainIndustries: ['传统医药', '草药', '食品', '贸易'],
    summary: '传统医药体系完整，华人商圈有消费基础，渠道建设处于早期红利期',
    description: '缅甸拥有完整的传统医药体系，当地华人商圈对中医药有较强消费基础。中缅边境贸易活跃，缅甸传统医药与中国中医药在药材使用上有交叉。渠道建设处于早期，进入成本较低。',
    opportunityCount: 4,
    color: '#27ae60',
  },
  {
    id: 'af',
    nameZh: '阿富汗',
    nameEn: 'Afghanistan',
    flag: '🇦🇫',
    tier: 3,
    region: '南亚',
    gdp: '200亿',
    population: '4300万',
    gdpPerCapita: '460',
    mainIndustries: ['传统草药', '食品', '干果出口'],
    summary: '传统草药资源丰富，中国企业可参与战后重建商机，能源和农业合作机会多',
    description: '阿富汗拥有丰富的传统草药资源，但医药市场尚在重建中。ACCI（阿富汗工商会）提供贸易促进服务，中国企业可通过贸易对接、投资合作等方式参与阿富汗市场重建。',
    opportunityCount: 3,
    color: '#c0392b',
  },
];

export const TIER_LABELS: Record<1 | 2 | 3, string> = {
  1: '第一梯队',
  2: '第二梯队',
  3: '第三梯队',
};

export const TIER_COLORS: Record<1 | 2 | 3, string> = {
  1: '#f59e0b',
  2: '#9ca3af',
  3: '#cd7f32',
};

export function getCountryById(id: string): Country | undefined {
  return COUNTRIES.find((c) => c.id === id);
}

export function getCountriesByTier(tier: 1 | 2 | 3): Country[] {
  return COUNTRIES.filter((c) => c.tier === tier);
}
