import { NewsArticle, TradeData, BusinessOpportunity, PricingPlan } from '@/types';

export const mockNews: NewsArticle[] = [
  {
    id: '1',
    title: '日本2024年对华直接投资创历史新高，制造业回流趋势明显',
    titleCn: '日本2024年对华直接投资创历史新高，制造业回流趋势明显',
    summary: '日本财务省数据显示，2024年日本对华直接投资达到235亿美元，同比增长12.3%，其中高端制造业和绿色能源领域投资增长尤为显著。',
    summaryCn: '日本财务省数据显示，2024年日本对华直接投资达到235亿美元，同比增长12.3%，其中高端制造业和绿色能源领域投资增长尤为显著。',
    source: '日本经济新闻',
    sourceUrl: 'https://www.nikkei.com',
    category: 'trade',
    country: 'bilateral',
    tags: ['投资', '制造业', '绿色能源'],
    publishedAt: '2026-03-28T10:30:00Z',
    isFeatured: true,
  },
  {
    id: '2',
    title: '中国商务部发布《中日经贸合作白皮书》，提出30项合作倡议',
    titleCn: '中国商务部发布《中日经贸合作白皮书》，提出30项合作倡议',
    summary: '白皮书涵盖数字经济、绿色低碳、医疗健康、现代农业等八大重点领域，提出构建中日新时代务实合作新格局的具体措施。',
    summaryCn: '白皮书涵盖数字经济、绿色低碳、医疗健康、现代农业等八大重点领域，提出构建中日新时代务实合作新格局的具体措施。',
    source: '商务部官网',
    sourceUrl: 'https://www.mofcom.gov.cn',
    category: 'policy',
    country: 'bilateral',
    tags: ['政策', '白皮书', '数字经济'],
    publishedAt: '2026-03-27T08:00:00Z',
    isFeatured: true,
  },
  {
    id: '3',
    title: '东京电力与中国国家电网签署智能电网合作协议',
    titleCn: '东京电力与中国国家电网签署智能电网合作协议',
    summary: '双方将在可再生能源并网、储能技术、电力市场改革等领域开展深度合作，项目总规模预计达50亿美元。',
    summaryCn: '双方将在可再生能源并网、储能技术、电力市场改革等领域开展深度合作，项目总规模预计达50亿美元。',
    source: '共同社',
    sourceUrl: 'https://kyodo.co.jp',
    category: 'industry',
    country: 'jp',
    tags: ['电力', '智能电网', '合作'],
    publishedAt: '2026-03-26T14:20:00Z',
  },
  {
    id: '4',
    title: '中日贸易额突破3800亿美元，锂电池和半导体材料成新增长点',
    titleCn: '中日贸易额突破3800亿美元，锂电池和半导体材料成新增长点',
    summary: '据海关总署统计，2025年中日双边贸易额达3847亿美元，其中锂电池产业链产品和半导体材料贸易增速超过40%。',
    summaryCn: '据海关总署统计，2025年中日双边贸易额达3847亿美元，其中锂电池产业链产品和半导体材料贸易增速超过40%。',
    source: '海关总署',
    sourceUrl: 'http://www.customs.gov.cn',
    category: 'trade',
    country: 'bilateral',
    tags: ['贸易额', '锂电池', '半导体'],
    publishedAt: '2026-03-25T09:15:00Z',
  },
  {
    id: '5',
    title: '日本农林水产省扩大中国产食品进口清单，清单数量增至328项',
    titleCn: '日本农林水产省扩大中国产食品进口清单，清单数量增至328项',
    summary: '日本农林水产省宣布更新进口食品清单，新增42项中国产食品，包括部分水产品和农产品，进一步便利中日农产品贸易。',
    summaryCn: '日本农林水产省宣布更新进口食品清单，新增42项中国产食品，包括部分水产品和农产品，进一步便利中日农产品贸易。',
    source: '农林水产省',
    sourceUrl: 'https://www.maff.go.jp',
    category: 'policy',
    country: 'jp',
    tags: ['农业', '食品', '进口'],
    publishedAt: '2026-03-24T11:00:00Z',
  },
  {
    id: '6',
    title: '日本企业浙江投资热潮：丰田联手比亚迪建第三工厂',
    titleCn: '日本企业浙江投资热潮：丰田联手比亚迪建第三工厂',
    summary: '丰田汽车与比亚迪联合宣布，将在浙江投资25亿美元建设新能源整车工厂，年产能30万辆，预计2027年投产。',
    summaryCn: '丰田汽车与比亚迪联合宣布，将在浙江投资25亿美元建设新能源整车工厂，年产能30万辆，预计2027年投产。',
    source: '朝日新闻',
    sourceUrl: 'https://www.asahi.com',
    category: 'industry',
    country: 'cn',
    tags: ['汽车', '新能源', '投资'],
    publishedAt: '2026-03-23T16:45:00Z',
  },
  {
    id: '7',
    title: '第28届上海国际工业博览会今日开幕，200家日企参展',
    titleCn: '第28届上海国际工业博览会今日开幕，200家日企参展',
    summary: '本届工博会以"智能制造与绿色转型"为主题，展位面积达36万平方米，参展日企数量同比增长18%，创历届之最。',
    summaryCn: '本届工博会以"智能制造与绿色转型"为主题，展位面积达36万平方米，参展日企数量同比增长18%，创历届之最。',
    source: '东博会组委会',
    sourceUrl: 'https://ciif.ciip-expo.com',
    category: 'event',
    country: 'cn',
    tags: ['展会', '工博会', '智能制造'],
    publishedAt: '2026-03-22T08:30:00Z',
  },
  {
    id: '8',
    title: '日元贬值推动中日电商贸易爆发，跨境平台GMV增长67%',
    titleCn: '日元贬值推动中日电商贸易爆发，跨境平台GMV增长67%',
    summary: '受日元持续走弱影响，日本消费者海淘中国商品热情高涨，阿里巴巴速卖通和拼多多Temu在日用户数均突破500万。',
    summaryCn: '受日元持续走弱影响，日本消费者海淘中国商品热情高涨，阿里巴巴速卖通和拼多多Temu在日用户数均突破500万。',
    source: 'Nikkei Asia',
    sourceUrl: 'https://asia.nikkei.com',
    category: 'market',
    country: 'jp',
    tags: ['电商', '日元', '跨境'],
    publishedAt: '2026-03-21T10:00:00Z',
  },
  {
    id: '9',
    title: '中日医药合作进入深水区，仿制药一致性评价合作加速',
    titleCn: '中日医药合作进入深水区，仿制药一致性评价合作加速',
    summary: '国家药监局与日本PMDA签署联合声明，在药品审评、监管科学、临床试验等领域深化合作，推动中日制药产业协同发展。',
    summaryCn: '国家药监局与日本PMDA签署联合声明，在药品审评、监管科学、临床试验等领域深化合作，推动中日制药产业协同发展。',
    source: '药监局官网',
    sourceUrl: 'https://www.nmpa.gov.cn',
    category: 'industry',
    country: 'bilateral',
    tags: ['医药', '仿制药', '监管'],
    publishedAt: '2026-03-20T13:00:00Z',
  },
  {
    id: '10',
    title: '中国恢复日本水产品进口，首批检验合格产品通关',
    titleCn: '中国恢复日本水产品进口，首批检验合格产品通关',
    summary: '中国海关总署公告称，恢复进口日本福岛等10个都县以外地区的水产品，首批通过检验的扇贝和海参产品已顺利通关。',
    summaryCn: '中国海关总署公告称，恢复进口日本福岛等10个都县以外地区的水产品，首批通过检验的扇贝和海参产品已顺利通关。',
    source: '新华社',
    sourceUrl: 'https://www.xinhuanet.com',
    category: 'trade',
    country: 'cn',
    tags: ['水产品', '进口', '通关'],
    publishedAt: '2026-03-19T15:30:00Z',
  },
];

export const mockTradeData: TradeData[] = [
  {
    id: '1',
    hsCode: '8471',
    productName: '自动数据处理设备及部件',
    productNameJp: '自動データ処理装置及びその部品',
    cnExport: 125400,
    cnImport: 89200,
    jpExport: 45600,
    jpImport: 134500,
    trend: 'up',
    trendPercent: 8.3,
    month: '2026-02',
    year: 2026,
  },
  {
    id: '2',
    hsCode: '8542',
    productName: '集成电路及微电子组件',
    productNameJp: '電子、集積回路',
    cnExport: 98200,
    cnImport: 156800,
    jpExport: 67800,
    jpImport: 134200,
    trend: 'up',
    trendPercent: 12.1,
    month: '2026-02',
    year: 2026,
  },
  {
    id: '3',
    hsCode: '8507',
    productName: '锂离子蓄电池',
    productNameJp: 'リチウムイオン蓄電池',
    cnExport: 78900,
    cnImport: 23400,
    jpExport: 12300,
    jpImport: 82300,
    trend: 'up',
    trendPercent: 23.5,
    month: '2026-02',
    year: 2026,
  },
  {
    id: '4',
    hsCode: '8703',
    productName: '汽车及汽车底盘',
    productNameJp: '自動車及びその部品',
    cnExport: 45600,
    cnImport: 67800,
    jpExport: 89200,
    jpImport: 56700,
    trend: 'down',
    trendPercent: -5.2,
    month: '2026-02',
    year: 2026,
  },
  {
    id: '5',
    hsCode: '0306',
    productName: '鲜活及冷冻水产品',
    productNameJp: '生きている魚、冷凍魚',
    cnExport: 23400,
    cnImport: 34500,
    jpExport: 45600,
    jpImport: 12300,
    trend: 'up',
    trendPercent: 18.7,
    month: '2026-02',
    year: 2026,
  },
  {
    id: '6',
    hsCode: '5201',
    productName: '纺织纱线及织物',
    productNameJp: '紡織用糸及び織物',
    cnExport: 56700,
    cnImport: 12300,
    jpExport: 8900,
    jpImport: 67800,
    trend: 'stable',
    trendPercent: 1.2,
    month: '2026-02',
    year: 2026,
  },
  {
    id: '7',
    hsCode: '8473',
    productName: '机械零部件及附件',
    productNameJp: '機械類用の部品',
    cnExport: 34500,
    cnImport: 45600,
    jpExport: 56700,
    jpImport: 34500,
    trend: 'up',
    trendPercent: 6.8,
    month: '2026-02',
    year: 2026,
  },
  {
    id: '8',
    hsCode: '3004',
    productName: '医药品及制剂',
    productNameJp: '医薬品（制剂を含む）',
    cnExport: 12300,
    cnImport: 34500,
    jpExport: 56700,
    jpImport: 23400,
    trend: 'up',
    trendPercent: 9.4,
    month: '2026-02',
    year: 2026,
  },
];

export const mockOpportunities: BusinessOpportunity[] = [
  {
    id: '1',
    title: '中国精密机械零部件企业对日出口合作',
    titleJp: '中国精密機械部品企業の日本輸出協力',
    description: '专业从事CNC精密加工的企业，寻求日本汽车零部件和工业设备制造商长期合作，提供精密轴类、齿轮箱体等部件。',
    descriptionJp: 'CNC精密加工 전문 기업으로 일본 자동차 부품 및 산업 설비 제조업체와 장기 협력 관계를 모색하고 있습니다.',
    type: 'supply',
    country: 'cn',
    industry: '精密制造',
    amount: '5000万',
    currency: 'CNY',
    companyName: '苏州精密智造科技有限公司',
    contactEmail: 'export@szjmtech.com',
    publishedAt: '2026-03-25T10:00:00Z',
    expiresAt: '2026-06-25T10:00:00Z',
    status: 'active',
    isPremium: true,
    region: '江苏省苏州市',
  },
  {
    id: '2',
    title: '日本高端化妆品原料寻求中国独家代理商',
    titleJp: '日本高級化粧品原料の中国独占代理店募集',
    description: '日本知名化妆品原料厂商，寻求中国独家代理商，负责EGF、FGF等高端抗衰老原料的市场推广和销售。',
    descriptionJp: '日本の有名化粧品原料メーカーが、中国市場の独占代理店を探しています。EGF、FGFなどの高級抗衰老原料のマーケティングと販売を担当します。',
    type: 'demand',
    country: 'jp',
    industry: '化妆品原料',
    amount: '1亿',
    currency: 'JPY',
    companyName: '東京精華化成株式会社',
    companyNameJp: '東京精華化成株式会社',
    contactEmail: 'china@tokyoseika.co.jp',
    publishedAt: '2026-03-24T08:00:00Z',
    expiresAt: '2026-05-24T08:00:00Z',
    status: 'active',
    isPremium: true,
    region: '东京都',
  },
  {
    id: '3',
    title: '中国新能源电池企业收购日本回收处理设备',
    titleJp: '中国新能源バッテリー企業の日本リサイクル処理設備買収',
    description: '计划收购日本退役锂电池回收处理设备及技术，包含破碎分选、湿法冶金等全套工艺，包年预算5000万人民币。',
    descriptionJp: '日本の使用済みリチウム電池リサイクル処理設備と技術の買収を計画。破砕分級、湿式冶金などの全套工程を含み、予算は年間5000万元。',
    type: 'investment',
    country: 'cn',
    industry: '新能源·储能',
    amount: '5000万',
    currency: 'CNY',
    companyName: '宁德时代新能源材料有限公司',
    contactEmail: 'm&a@catl-ne.com',
    publishedAt: '2026-03-23T14:30:00Z',
    expiresAt: '2026-04-23T14:30:00Z',
    status: 'active',
    isPremium: false,
    region: '福建省宁德市',
  },
  {
    id: '4',
    title: '中日医疗器械联合研发项目招募合作伙伴',
    titleJp: '中日医療器械共同研究開発プロジェクトのパートナー募集',
    description: '拟开展消化内镜AI辅助诊断系统联合研发，中方提供数据集和临床资源，日方提供图像处理算法，共享知识产权。',
    descriptionJp: '消化器内視鏡AI補助診断システムの共同研究開発を計画。中方はデータセットと臨床リソースを提供し、日方は画像処理アルゴリズムを提供し知的財産権を共有。',
    type: 'cooperation',
    country: 'bilateral',
    industry: '医疗器械',
    companyName: '奥林巴斯（北京）医疗器械有限公司',
    companyNameJp: 'オリンパス（北京）医療器械有限公司',
    contactEmail: 'rd@olympus-bj.com.cn',
    publishedAt: '2026-03-22T09:00:00Z',
    expiresAt: '2026-07-22T09:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: '5',
    title: '中国有机农产品对日出口（有机大米、特色食用菌）',
    titleJp: '中国有機農産物の日本輸出（有機米、特色食用キノコ）',
    description: '持有日本JAS有机认证的农产品企业，现寻求日本进口商合作，出口有机大米、野生菌菇等东北特色农产品。',
    descriptionJp: '日本のJAS有機認証を取得した農産物企業で、日本輸入業者との協力を求めています。有機米、野生キノコなどの東北特色農産物を輸出。',
    type: 'supply',
    country: 'cn',
    industry: '现代农业',
    amount: '2000万',
    currency: 'CNY',
    companyName: '黑龙江省绿色农业集团',
    contactEmail: 'export@hljsnwy.com',
    publishedAt: '2026-03-21T11:00:00Z',
    expiresAt: '2026-06-21T11:00:00Z',
    status: 'active',
    isPremium: false,
    region: '黑龙江省哈尔滨市',
  },
  {
    id: '6',
    title: '日本工业机器人系统集成商寻求中国代理商',
    titleJp: '日本産業ロボットシステムインテグレーターの中国代理店募集',
    description: '专注汽车焊装和总装工序的日本机器人系统集成商，寻求中国代理商合作，目标是2026年在华销售额突破5亿日元。',
    descriptionJp: '自動車ボディ溶接・最終組立工程を専門とする日本のロボットシステムインテグレーターが、中国代理店を探している。2026年の中国での売上高5億円突破が目標。',
    type: 'demand',
    country: 'jp',
    industry: '智能制造',
    amount: '5亿',
    currency: 'JPY',
    companyName: '株式会社安川電機エンジニアリング',
    contactEmail: 'china-partner@yaskawa-eng.co.jp',
    publishedAt: '2026-03-20T08:00:00Z',
    expiresAt: '2026-05-20T08:00:00Z',
    status: 'active',
    isPremium: true,
    region: '爱知县',
  },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: '免费版',
    nameJp: '無料版',
    tagline: '入门首选，了解中日经贸动态',
    taglineJp: '入門向け、中日经贸の動向を把握',
    price: 0,
    priceUnit: 'month',
    currency: 'CNY',
    features: [
      '每日5条精选商机推送',
      '浏览公开经贸资讯',
      '查看基础贸易数据',
      '收藏感兴趣的内容',
    ],
    cta: '免费开始',
  },
  {
    id: 'pro',
    name: '专业版',
    nameJp: 'プロフェッショナル版',
    tagline: '适合贸易从业者和企业决策者',
    taglineJp: '貿易従事者や企業意思決定者に最適',
    price: 299,
    priceUnit: 'month',
    currency: 'CNY',
    highlighted: true,
    badge: '最受欢迎',
    features: [
      '无限浏览商机信息',
      '中日贸易数据API访问',
      '每周商机快讯推送',
      '商机收藏与跟踪',
      '邮件咨询支持',
      '优先展示给日方企业',
    ],
    cta: '立即升级',
  },
  {
    id: 'enterprise',
    name: '企业版',
    nameJp: 'エンタープライズ版',
    tagline: '适合大型企业和专业咨询机构',
    taglineJp: '大企業や専門コンサルティング機関に最適',
    price: 999,
    priceUnit: 'month',
    currency: 'CNY',
    features: [
      '专业版全部功能',
      '完整贸易数据库访问',
      '行业深度分析报告（月刊）',
      'B2B商机精准匹配服务',
      '专属客户经理支持',
      '企业品牌展示位',
      '线下活动优先报名权',
    ],
    cta: '联系我们',
  },
];
