import { BusinessOpportunity, PricingPlan } from '@/types';

export const mockOpportunities: BusinessOpportunity[] = [
  {
    id: 'opp-001',
    title: '东京地区寻求中国高端医疗器械代理合作',
    titleEn: 'Seeking China Premium Medical Device Agency in Tokyo',
    description: '日本东京某医疗器械分销商，寻求中国高端医疗器械（影像设备、手术机器人、植入耗材）的日本市场独家代理权。要求产品已获得PMDA注册，具备日本语说明书和售后服务能力。',
    descriptionEn: 'Tokyo-based medical device distributor seeks exclusive agency for Chinese premium medical devices already PMDA-registered in Japan.',
    type: 'demand',
    country: 'japan',
    region: 'jp-tokyo',
    regionLabel: '东京首都圈',
    industry: '医疗器械',
    cooperationType: 'agency',
    amount: '500',
    currency: 'USD',
    companyName: '东京医研贸易株式会社',
    companyNameEn: 'Tokyo Iken Trading Co., Ltd.',
    contactEmail: 'partner@tokyo-iken.jp',
    publishedAt: '2026-03-25T08:00:00Z',
    expiresAt: '2026-06-25T08:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'opp-002',
    title: '大阪关西制造商寻中国工业机器人零部件供应商',
    titleEn: 'Osaka Manufacturer Seeks China Industrial Robot Parts Supplier',
    description: '关西地区某工业机器人制造商，急需采购中国制造的谐波减速器、伺服电机和控制器。要求稳定的批量供货能力，品质对标日本标准，交货周期不超过3周。',
    descriptionEn: 'Osaka industrial robot manufacturer urgently needs Chinese harmonic reducers, servo motors, and controllers.',
    type: 'demand',
    country: 'japan',
    region: 'jp-osaka',
    regionLabel: '大阪关西圈',
    industry: '工业自动化',
    cooperationType: 'distribution',
    amount: '200',
    currency: 'USD',
    companyName: '関西オートメーション株式会社',
    companyNameEn: 'Kansai Automation Co., Ltd.',
    contactEmail: 'procurement@ka-autocon.jp',
    publishedAt: '2026-03-24T10:00:00Z',
    expiresAt: '2026-05-24T10:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'opp-003',
    title: '首尔半导体材料商寻求中国硅晶圆供应商',
    titleEn: 'Seoul Semiconductor Materials Firm Seeks China Silicon Wafer Supplier',
    description: '韩国半导体材料分销商，因业务扩张，急需采购8英寸和12英寸硅晶圆。要求中国主流厂商产品，有SGS或同等认证，批量供货稳定。',
    descriptionEn: 'Korean semiconductor materials distributor seeks 8-inch and 12-inch silicon wafers from Chinese manufacturers.',
    type: 'demand',
    country: 'south-korea',
    region: 'kr-seoul',
    regionLabel: '首尔首都圈',
    industry: '半导体/电子',
    cooperationType: 'agency',
    amount: '800',
    currency: 'USD',
    companyName: '京畿半导体材料',
    companyNameEn: 'Gyeonggi Semiconductor Materials Co.',
    contactEmail: 'buy@gsemico.kr',
    publishedAt: '2026-03-26T09:00:00Z',
    expiresAt: '2026-06-26T09:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'opp-004',
    title: '胡志明市家具贸易商急寻中国实木家具供应商',
    titleEn: 'HCMC Furniture Trader Urgently Seeks China Solid Wood Furniture Supplier',
    description: '越南胡志明市家具进口贸易商，因现有供应商断供，急需寻找中国实木家具（橡木、松木）供应商。要求月供货量200套以上，可FOB胡志明市。',
    descriptionEn: 'HCMC furniture importer urgently needs Chinese solid wood furniture (oak/pine) supplier with 200+ sets/month capacity.',
    type: 'demand',
    country: 'vietnam',
    region: 'vn-hcmc',
    regionLabel: '胡志明市南越经济圈',
    industry: '家具制造',
    cooperationType: 'agency',
    amount: '80',
    currency: 'USD',
    companyName: '越南家居进出口公司',
    companyNameEn: 'Vina Home Import & Export Co.',
    contactEmail: 'dung@vina-home.vn',
    publishedAt: '2026-03-28T05:00:00Z',
    expiresAt: '2026-04-28T05:00:00Z',
    status: 'active',
    isPremium: false,
  },
  {
    id: 'opp-005',
    title: '吉隆坡电子制造商寻求中国消费级锂电池供应商',
    titleEn: 'KL Electronics Manufacturer Seeks China Consumer Li-ion Battery Supplier',
    description: '马来西亚吉隆坡消费电子制造商，为其电动工具和移动电源产品线，寻求中国18650/21700锂电池和PACK供应商。要求有UL、IEC认证，出口马来西亚经验。',
    descriptionEn: 'KL consumer electronics manufacturer seeks Chinese 18650/21700 li-ion batteries and PACK suppliers.',
    type: 'demand',
    country: 'malaysia',
    region: 'my-kl',
    regionLabel: '吉隆坡雪兰莪',
    industry: '消费电子',
    cooperationType: 'agency',
    amount: '250',
    currency: 'USD',
    companyName: '绿色能量电子马来西亚',
    companyNameEn: 'GreenPower Electronics Malaysia',
    contactEmail: 'china@gpem.my',
    publishedAt: '2026-03-25T09:00:00Z',
    expiresAt: '2026-06-25T09:00:00Z',
    status: 'active',
    isPremium: true,
  },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: '免费版',
    nameEn: 'Free',
    tagline: '入门首选，开始发现亚洲商机',
    taglineEn: 'Start discovering Asia business opportunities',
    price: 0,
    priceUnit: 'month',
    currency: 'CNY',
    features: [
      '浏览全部商机信息',
      '查看13国市场概览',
      '收藏感兴趣商机',
      '接收每周精选商机邮件',
    ],
    featuresEn: [
      'Browse all opportunities',
      'View 13 country market overviews',
      'Save favorite opportunities',
      'Receive weekly curated emails',
    ],
    cta: '免费开始',
  },
  {
    id: 'pro',
    name: '专业版',
    nameEn: 'Professional',
    tagline: '适合有出海计划的贸易从业者和企业决策者',
    taglineEn: 'For trade professionals and business decision-makers with outbound plans',
    price: 299,
    priceUnit: 'month',
    currency: 'CNY',
    highlighted: true,
    badge: '最受欢迎',
    features: [
      '免费版全部功能',
      '无限联系商机发布方',
      '优先展示给海外合作伙伴',
      '解锁全部行业版块报告',
      '专属出海顾问咨询（每月1次）',
      '优先发布商机（每月3条）',
    ],
    featuresEn: [
      'All Free features',
      'Unlimited contact opportunity issuers',
      'Priority visibility to overseas partners',
      'Unlock all industry sector reports',
      'Dedicated outbound advisor (1x/month)',
      'Priority opportunity posting (3/month)',
    ],
    cta: '立即升级',
  },
  {
    id: 'enterprise',
    name: '企业版',
    nameEn: 'Enterprise',
    tagline: '适合大型制造企业、上市公司和咨询机构',
    taglineEn: 'For large manufacturers, listed companies, and consulting firms',
    price: 999,
    priceUnit: 'month',
    currency: 'CNY',
    features: [
      '专业版全部功能',
      '定制国别市场研究报告',
      'B2B精准商机匹配服务',
      '全年不限次出海顾问咨询',
      '企业品牌专属展示位',
      '线下出海峰會优先报名',
      '竞品动态监控预警',
    ],
    featuresEn: [
      'All Professional features',
      'Custom country market research reports',
      'B2B precision opportunity matching',
      'Unlimited outbound advisor access',
      'Dedicated brand showcase placement',
      'Priority access to offline summits',
      'Competitor dynamics monitoring alerts',
    ],
    cta: '联系我们',
  },
];
