#!/usr/bin/env node
/**
 * 清理 opportunities.json 中的噪音条目并补充高质量人工商机
 * Run: node scripts/cleanAndSeedData.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, '..', 'public', 'data', 'opportunities.json');

// ── Noise patterns ─────────────────────────────────────────────────────────
const NOISE_PATTERNS = [
  /Quote of the Day/i,
  /Taylor Swift/i,
  /Steve Jobs/i,
  /Bill Gates/i,
  /Dogs can.*digest/i,
  /Harbhajan Singh/i,
  /Houthis|Hamas|Gaza|Israel.*war|Palestine|mideast war/i,
  /Russia.*Ukraine|Ukraine.*Putin|Zelensky/i,
  /Gold price|油价|金价|gia vàng|石油価格/i,
  /株[javas]/,
  /美容|美妆|整形|K-POP|Kpop|韩流/i,
  /Taylor Swift|Bill Gates Quote|Steve Jobs Quote/i,
  /Iran war|Iran negotiation|Iran stalemate/i,
  /OECD.*韩国.*成长/,
  / máscara|要素수|生필품/,
  /地震|震度|台风|海啸/i,
  /COVID|pandemic|感染|疫情/,
];

function isNoise(entry) {
  const text = (entry.title + ' ' + entry.description).toLowerCase();
  // No dataSource = manual entry → always keep
  if (!entry.dataSource) return false;
  // Has dataSource → check noise patterns
  for (const pat of NOISE_PATTERNS) {
    if (pat.test(text)) return true;
  }
  // Very generic business news that isn't about actual trade/BD
  if (entry.industry === '综合商务' && entry.dataSource) {
    // Keep entries with region labels (more specific)
    if (!entry.regionLabel) return true;
  }
  return false;
}

// ── High-quality manual entries (no dataSource) ────────────────────────────
// Covering: 13 countries × multiple industries × supply/demand/investment/cooperation types
const MANUAL_ENTRIES = [
  // ═══════════════════ 日本 Japan (Tier 1) ═══════════════════
  {
    id: 'manual-jp-001',
    title: '东京医疗器械分销商寻求中国高端影像设备代理权',
    titleEn: 'Tokyo Medical Device Distributor Seeks China Premium Imaging Equipment Agency',
    description: '日本东京某医疗器械专业分销商，寻求中国高端医学影像设备（CT、MRI、超声）的日本市场独家代理。要求产品已获得PMDA认证，具备日语说明书和本地售后服务网络。',
    descriptionEn: 'Tokyo-based medical device distributor seeks exclusive agency for Chinese premium medical imaging equipment (CT, MRI, ultrasound) with PMDA registration and Japanese after-sales service.',
    type: 'demand',
    country: 'japan',
    region: 'jp-tokyo',
    regionLabel: '东京首都圈',
    industry: '医疗器械',
    cooperationType: 'agency',
    amount: '500',
    currency: 'USD',
    companyName: '东邦医疗贸易株式会社',
    companyNameEn: 'Toho Medical Trading Co., Ltd.',
    contactEmail: 'partner@tohomedical.jp',
    publishedAt: '2026-03-25T08:00:00Z',
    expiresAt: '2026-06-25T08:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-jp-002',
    title: '关西工业机器人制造商急寻中国谐波减速器供应商',
    titleEn: 'Osaka Robot Manufacturer Urgently Seeks China Harmonic Reducer Supplier',
    description: '关西地区某工业机器人制造商，因现有供应商断供，急需采购中国制造的谐波减速器和伺服电机。要求品质对标日本JIS标准，月供货量500台以上，交货周期不超过3周。',
    descriptionEn: 'Osaka industrial robot manufacturer urgently needs Chinese harmonic reducers and servo motors. JIS standard required, 500+ units/month, max 3-week delivery.',
    type: 'demand',
    country: 'japan',
    region: 'jp-osaka',
    regionLabel: '大阪关西圈',
    industry: '工业自动化',
    cooperationType: 'distribution',
    amount: '200',
    currency: 'USD',
    companyName: '関西オートメーション株式会社',
    companyNameEn: 'Kansai Automation Co., Ltd.',
    contactEmail: 'procurement@ka-autocon.jp',
    publishedAt: '2026-03-24T10:00:00Z',
    expiresAt: '2026-05-24T10:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-jp-003',
    title: '静冈食品企业寻求中国有机茶原料长期供应合作',
    titleEn: 'Shizuoka Food Company Seeks China Organic Tea Supply Partnership',
    description: '静冈县某有机食品加工企业，希望从中国采购有机茶叶原料（乌龙茶、绿茶、普洱），用于生产面向日本高端市场的有机茶饮料。需具备有机认证和SGS检测报告。',
    descriptionEn: 'Shizuoka organic food company seeks long-term supply of organic Chinese tea (oolong, green, pu-erh) for premium organic tea beverages. Organic certification and SGS reports required.',
    type: 'demand',
    country: 'japan',
    region: 'jp-nagoya',
    regionLabel: '爱知名古屋圈',
    industry: '食品农业',
    cooperationType: 'supply',
    amount: '80',
    currency: 'USD',
    companyName: '富士山食品株式会社',
    companyNameEn: 'Fujisan Foods Co., Ltd.',
    contactEmail: 'import@fujisan-foods.jp',
    publishedAt: '2026-03-20T06:00:00Z',
    expiresAt: '2026-06-20T06:00:00Z',
    status: 'active',
    isPremium: false,
  },
  {
    id: 'manual-jp-004',
    title: '寻求中国有机护肤品牌日本市场代理',
    titleEn: 'Seeking China Organic Skincare Brand Japan Agency',
    description: '上海某有机护肤品牌已完成日本COSMOS有机认证，现寻求日本市场代理合作伙伴。要求有日本美妆产品运营经验，有药妆店或百货渠道资源优先。',
    descriptionEn: 'Shanghai organic skincare brand with Japanese COSMOS certification seeks Japan market agency partner with cosmetics retail or department store channel resources.',
    type: 'supply',
    country: 'japan',
    region: 'jp-tokyo',
    regionLabel: '东京首都圈',
    industry: '美妆护肤',
    cooperationType: 'agency',
    amount: '50',
    currency: 'USD',
    companyName: '上海芳典生物科技',
    companyNameEn: 'Shanghai Fangdian Biotech Co.',
    contactEmail: 'japan@fangdian.cn',
    publishedAt: '2026-03-27T06:00:00Z',
    expiresAt: '2026-06-27T06:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-jp-005',
    title: '东京自动化设备商寻求中国协作机器人（cobots）进口代理',
    titleEn: 'Tokyo Automation Company Seeks China Collaborative Robot Import Agency',
    description: '东京某工厂自动化集成商，寻求中国协作机器人（cobot）制造商的产品代理权。要求产品安全认证齐全（CE/UL），支持开放API，已有在日实际应用案例优先。',
    descriptionEn: 'Tokyo factory automation integrator seeks agency for Chinese collaborative robot (cobot) manufacturers. CE/UL certified, open API support, existing Japan use cases preferred.',
    type: 'demand',
    country: 'japan',
    region: 'jp-tokyo',
    regionLabel: '东京首都圈',
    industry: '工业自动化',
    cooperationType: 'agency',
    amount: '150',
    currency: 'USD',
    companyName: '东洋自动化システム',
    companyNameEn: 'Toyo Automation Systems Co., Ltd.',
    contactEmail: 'cobot@toyso-auto.jp',
    publishedAt: '2026-03-15T08:00:00Z',
    expiresAt: '2026-06-15T08:00:00Z',
    status: 'active',
    isPremium: true,
  },

  // ═══════════════════ 韩国 South Korea (Tier 1) ═══════════════════
  {
    id: 'manual-kr-001',
    title: '首尔半导体材料商寻求中国8/12英寸硅晶圆供应商',
    titleEn: 'Seoul Semiconductor Materials Firm Seeks China Silicon Wafer Supplier',
    description: '韩国半导体材料分销商，因业务扩张，急需采购8英寸和12英寸硅晶圆。要求中国主流厂商产品，有SGS或同等认证，批量供货稳定，已有向韩国出口记录优先。',
    descriptionEn: 'Korean semiconductor materials distributor seeks 8-inch and 12-inch silicon wafers from Chinese manufacturers with SGS certification and stable batch supply.',
    type: 'demand',
    country: 'south-korea',
    region: 'kr-seoul',
    regionLabel: '首尔首都圈',
    industry: '半导体/电子',
    cooperationType: 'agency',
    amount: '800',
    currency: 'USD',
    companyName: '京畿半导体材料',
    companyNameEn: 'Gyeonggi Semiconductor Materials Co.',
    contactEmail: 'buy@gsemico.kr',
    publishedAt: '2026-03-26T09:00:00Z',
    expiresAt: '2026-06-26T09:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-kr-002',
    title: '釜山显示器件商寻求中国OLED面板供应商合作',
    titleEn: 'Busan Display Company Seeks China OLED Panel Supplier',
    description: '釜山某显示器件贸易商，正在为韩国某电视品牌寻找OLED面板供应商。要求中国面板厂商产品，品质达A规，可提供技术支持和退换货服务。',
    descriptionEn: 'Busan display trading company seeks OLED panel supplier for Korean TV brand. Chinese panel manufacturers preferred, Grade A quality, technical support and return policy required.',
    type: 'demand',
    country: 'south-korea',
    region: 'kr-busan',
    regionLabel: '釜山岭南圈',
    industry: '消费电子',
    cooperationType: 'supply',
    amount: '300',
    currency: 'USD',
    companyName: '岭南光电贸易',
    companyNameEn: 'Yeongnam Opto Electronics Trading',
    contactEmail: 'procure@ynoptokr.kr',
    publishedAt: '2026-03-18T09:00:00Z',
    expiresAt: '2026-06-18T09:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 新加坡 Singapore (Tier 1) ═══════════════════
  {
    id: 'manual-sg-001',
    title: '新加坡金融科技公司寻求东南亚支付系统中国硬件供应商',
    titleEn: 'Singapore Fintech Seeks China Hardware Supplier for SEA Payments',
    description: '新加坡金融科技创业公司，为其东南亚支付网关业务寻找中国POS终端、扫码枪和智能收银机供应商。要求CE/FCC认证，支持多语言系统，批量供货能力强。',
    descriptionEn: 'Singapore fintech startup seeks Chinese POS terminals, QR scanners and smart cash registers for Southeast Asia payment gateway. CE/FCC certified, multilingual support required.',
    type: 'demand',
    country: 'singapore',
    region: 'sg-central',
    regionLabel: '中城区',
    industry: '金融科技',
    cooperationType: 'supply',
    amount: '150',
    currency: 'USD',
    companyName: 'AsiaPay Gateway Pte. Ltd.',
    companyNameEn: 'AsiaPay Gateway Pte. Ltd.',
    contactEmail: 'hardware@asiapaygateway.sg',
    publishedAt: '2026-03-27T07:00:00Z',
    expiresAt: '2026-06-27T07:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-sg-002',
    title: '新加坡寻求中国AI语音识别技术授权合作',
    titleEn: 'Singapore Seeks China AI Speech Recognition Technology License',
    description: '新加坡某企业服务SaaS公司，寻求中国AI语音识别和自然语言处理技术授权，用于东南亚多语言客户服务场景。要求支持英语、马来语、泰语、越南语，技术成熟可落地。',
    descriptionEn: 'Singapore enterprise SaaS firm seeks Chinese AI speech recognition and NLP technology license for Southeast Asian multilingual customer service applications.',
    type: 'cooperation',
    country: 'singapore',
    region: 'sg-central',
    regionLabel: '中城区',
    industry: 'IT/软件',
    cooperationType: 'technology',
    amount: '200',
    currency: 'USD',
    companyName: '亚太智能服务',
    companyNameEn: 'Asia Pacific Intelligent Services',
    contactEmail: 'tech@ap-intelserv.sg',
    publishedAt: '2026-03-28T08:00:00Z',
    expiresAt: '2026-07-28T08:00:00Z',
    status: 'active',
    isPremium: false,
  },
  {
    id: 'manual-sg-003',
    title: '新加坡寻求中国冷链物流设备进口代理',
    titleEn: 'Singapore Seeks China Cold Chain Equipment Import Agency',
    description: '新加坡某冷链物流解决方案提供商，寻求中国冷链设备和冷藏车制造商的东南亚代理权。要求产品符合新加坡SLS标准，有ISO认证，已有食品冷链应用案例。',
    descriptionEn: 'Singapore cold chain logistics provider seeks China cold chain equipment and refrigerated vehicle manufacturers agency for Southeast Asia. SLS standard, ISO certified, food cold chain experience required.',
    type: 'demand',
    country: 'singapore',
    region: 'sg-west',
    regionLabel: '西部工业区',
    industry: '贸易/物流',
    cooperationType: 'agency',
    amount: '120',
    currency: 'USD',
    companyName: '星冷供应链 Pte. Ltd.',
    companyNameEn: 'Starchain Supply Chain Pte. Ltd.',
    contactEmail: 'coldchain@starchain.sg',
    publishedAt: '2026-03-12T07:00:00Z',
    expiresAt: '2026-06-12T07:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 越南 Vietnam (Tier 1) ═══════════════════
  {
    id: 'manual-vn-001',
    title: '胡志明市家具贸易商急寻中国实木家具供应商',
    titleEn: 'HCMC Furniture Trader Urgently Seeks China Solid Wood Furniture Supplier',
    description: '越南胡志明市家具进口贸易商，因现有供应商断供，急需寻找中国实木家具（橡木、松木）供应商。要求月供货量200套以上，可FOB胡志明市，提供原产地证书。',
    descriptionEn: 'HCMC furniture importer urgently needs Chinese solid wood furniture (oak/pine) supplier with 200+ sets/month capacity, FOB HCMC terms, certificate of origin provided.',
    type: 'demand',
    country: 'vietnam',
    region: 'vn-hcmc',
    regionLabel: '胡志明市南越经济圈',
    industry: '家具制造',
    cooperationType: 'supply',
    amount: '80',
    currency: 'USD',
    companyName: '越南家居进出口公司',
    companyNameEn: 'Vina Home Import & Export Co.',
    contactEmail: 'dung@vina-home.vn',
    publishedAt: '2026-03-28T05:00:00Z',
    expiresAt: '2026-04-28T05:00:00Z',
    status: 'active',
    isPremium: false,
  },
  {
    id: 'manual-vn-002',
    title: '河内电子制造商寻求中国锂电池PACK供应商（月供5万支）',
    titleEn: 'Hanoi Electronics Maker Seeks China Li-ion Battery PACK Supplier (50K/month)',
    description: '越南北宁工业园区某电动工具制造商，寻求中国21700和18650锂电池PACK供应商。要求UL、IEC认证，月供货量5万支以上，有越南出口经验。',
    descriptionEn: 'Bac Ninh electronics manufacturer seeks Chinese 21700/18650 lithium battery PACK supplier. UL/IEC certified, 50K+/month supply, Vietnam export experience preferred.',
    type: 'demand',
    country: 'vietnam',
    region: 'vn-hanoi',
    regionLabel: '河内-北宁工业圈',
    industry: '消费电子',
    cooperationType: 'supply',
    amount: '150',
    currency: 'USD',
    companyName: '北宁天梭电子',
    companyNameEn: 'Bac Ninh Timesten Electronics Co.',
    contactEmail: 'battery@bntt.vn',
    publishedAt: '2026-03-20T05:00:00Z',
    expiresAt: '2026-06-20T05:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-vn-003',
    title: '胡志明市服装品牌寻求中国功能性面料供应商',
    titleEn: 'HCMC Fashion Brand Seeks China Functional Fabric Supplier',
    description: '越南时尚运动服装品牌，寻求中国供应商运动功能性面料（吸湿排汗、抗UV、抗菌）。要求有OEKO-TEX认证，月供货量10万米以上，有越南服装品牌合作记录优先。',
    descriptionEn: 'Vietnamese sportswear brand seeks Chinese functional fabrics (moisture-wicking, UV-protective, antibacterial). OEKO-TEX certified, 100K+ meters/month, Vietnamese apparel brand experience preferred.',
    type: 'demand',
    country: 'vietnam',
    region: 'vn-hcmc',
    regionLabel: '胡志明市南越经济圈',
    industry: '纺织服装',
    cooperationType: 'supply',
    amount: '100',
    currency: 'USD',
    companyName: '越南运动时尚进出口',
    companyNameEn: 'VietActive Trading Import Export Co.',
    contactEmail: 'fabric@vietactive.vn',
    publishedAt: '2026-03-15T05:00:00Z',
    expiresAt: '2026-06-15T05:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 马来西亚 Malaysia (Tier 2) ═══════════════════
  {
    id: 'manual-my-001',
    title: '吉隆坡电子制造商寻求中国消费级锂电池供应商',
    titleEn: 'KL Electronics Manufacturer Seeks China Consumer Li-ion Battery Supplier',
    description: '马来西亚吉隆坡消费电子制造商，为其电动工具和移动电源产品线，寻求中国18650/21700锂电池和PACK供应商。要求有UL、IEC认证，出口马来西亚经验。',
    descriptionEn: 'KL consumer electronics manufacturer seeks Chinese 18650/21700 li-ion batteries and PACK suppliers for power tools and power banks. UL/IEC certified, Malaysia export experience required.',
    type: 'demand',
    country: 'malaysia',
    region: 'my-kl',
    regionLabel: '吉隆坡雪兰莪',
    industry: '消费电子',
    cooperationType: 'agency',
    amount: '250',
    currency: 'USD',
    companyName: '绿色能量电子马来西亚',
    companyNameEn: 'GreenPower Electronics Malaysia',
    contactEmail: 'china@gpem.my',
    publishedAt: '2026-03-25T09:00:00Z',
    expiresAt: '2026-06-25T09:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-my-002',
    title: '槟城医疗器械商寻求中国一次性耗材OEM合作',
    titleEn: 'Penang Medical Device Company Seeks China Disposable Supplies OEM',
    description: '马来西亚槟城某医疗器械公司，希望寻找中国一次性医疗耗材（注射器、输液袋、敷料）制造商进行OEM合作。要求FDA或CE认证，可定制包装，有英语说明书。',
    descriptionEn: 'Penang medical device company seeks China disposable medical supplies (syringes, IV bags, wound dressings) OEM partner. FDA/CE certified, custom packaging, English instructions required.',
    type: 'cooperation',
    country: 'malaysia',
    region: 'my-penang',
    regionLabel: '槟城',
    industry: '医疗器械',
    cooperationType: 'oem',
    amount: '60',
    currency: 'USD',
    companyName: '绿光医疗科技 马来西亚',
    companyNameEn: 'GreenMedTech Malaysia Sdn. Bhd.',
    contactEmail: 'oem@greenmedtech.my',
    publishedAt: '2026-03-10T09:00:00Z',
    expiresAt: '2026-06-10T09:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 泰国 Thailand (Tier 2) ═══════════════════
  {
    id: 'manual-th-001',
    title: '曼谷汽车零部件商寻求中国新能源汽车驱动电机供应商',
    titleEn: 'Bangkok Auto Parts Company Seeks China EV Drive Motor Supplier',
    description: '泰国某汽车OEM零部件供应商，正在为日系电动汽车品牌寻找中国驱动电机（功率密度20kW/kg以上）供应商。要求有IATF16949认证，支持泰国本地化技术支持。',
    descriptionEn: 'Thai automotive OEM parts supplier seeks Chinese EV drive motors (power density 20kW/kg+) for Japanese EV brand. IATF16949 certified, local technical support in Thailand required.',
    type: 'demand',
    country: 'thailand',
    region: 'th-eea',
    regionLabel: '东部经济走廊',
    industry: '新能源汽车',
    cooperationType: 'supply',
    amount: '400',
    currency: 'USD',
    companyName: '暹罗汽车零部件',
    companyNameEn: 'Siam Auto Parts Co., Ltd.',
    contactEmail: 'ev@siaparts.co.th',
    publishedAt: '2026-03-22T06:00:00Z',
    expiresAt: '2026-06-22T06:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-th-002',
    title: '泰国食品出口商寻求中国有机橡胶原料供应',
    titleEn: 'Thai Food Exporter Seeks China Organic Rubber Raw Material Supply',
    description: '泰国某橡胶食品包装出口商，寻求中国有机橡胶原料供应商。要求有有机认证（EU或NOP），食品级标准，符合泰国FDA和出口目的地国标准。',
    descriptionEn: 'Thai rubber food packaging exporter seeks China organic rubber raw material supplier. Organic certification (EU or NOP), food-grade standard, Thai FDA and destination country compliance required.',
    type: 'demand',
    country: 'thailand',
    region: 'th-bangkok',
    regionLabel: '曼谷大都会区',
    industry: '化工材料',
    cooperationType: 'supply',
    amount: '50',
    currency: 'USD',
    companyName: '湄南食品包装',
    companyNameEn: 'Menam Food Packaging Co., Ltd.',
    contactEmail: 'raw@menampack.co.th',
    publishedAt: '2026-03-08T06:00:00Z',
    expiresAt: '2026-06-08T06:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 印尼 Indonesia (Tier 2) ═══════════════════
  {
    id: 'manual-id-001',
    title: '雅加达建材分销商寻求中国瓷砖和卫浴产品进口代理',
    titleEn: 'Jakarta Building Material Distributor Seeks China Tiles & Sanitary Ware Agency',
    description: '印尼雅加达某建材分销商，正在扩大产品线，寻求中国瓷砖、卫浴五金和厨房台面制造商的印尼市场代理权。要求有印尼SNI认证，产品设计符合东南亚审美。',
    descriptionEn: 'Jakarta building material distributor seeks China tiles, sanitary ware and kitchen countertop manufacturers agency for Indonesia. SNI certified, Southeast Asian design aesthetic required.',
    type: 'demand',
    country: 'indonesia',
    region: 'id-jakarta',
    regionLabel: '雅加达大区',
    industry: '房地产/建筑',
    cooperationType: 'agency',
    amount: '200',
    currency: 'USD',
    companyName: '雅加达金刚建材',
    companyNameEn: 'PT Jaya Building Materials Indonesia',
    contactEmail: 'china@jbi.co.id',
    publishedAt: '2026-03-15T08:00:00Z',
    expiresAt: '2026-06-15T08:00:00Z',
    status: 'active',
    isPremium: false,
  },
  {
    id: 'manual-id-002',
    title: '印尼电池回收企业寻求中国锂电池回收处理设备',
    titleEn: 'Indonesian Battery Recycler Seeks China Lithium Battery Recycling Equipment',
    description: '印尼某电池回收和处理企业，正在建设锂电池回收产线，寻求中国锂电池回收设备（破碎、分选、湿法冶金）供应商。要求有印尼项目案例，设备成熟稳定。',
    descriptionEn: 'Indonesian battery recycling company building lithium battery recycling line seeks Chinese equipment (crushing, sorting, hydrometallurgy). Indonesia project references and proven equipment required.',
    type: 'demand',
    country: 'indonesia',
    region: 'id-java',
    regionLabel: '爪哇其他地区',
    industry: '能源电力',
    cooperationType: 'supply',
    amount: '300',
    currency: 'USD',
    companyName: 'PT Indonesia Battery Cycle',
    companyNameEn: 'PT Indonesia Battery Cycle',
    contactEmail: 'equipment@ibcycle.id',
    publishedAt: '2026-03-18T08:00:00Z',
    expiresAt: '2026-06-18T08:00:00Z',
    status: 'active',
    isPremium: true,
  },

  // ═══════════════════ 菲律宾 Philippines (Tier 2) ═══════════════════
  {
    id: 'manual-ph-001',
    title: '马尼拉电子制造服务商寻求中国SMT贴片机设备供应商',
    titleEn: 'Manila EMS Company Seeks China SMT Placement Equipment Supplier',
    description: '菲律宾马尼拉某电子制造服务商（EMS），寻求中国SMT贴片机（AOI检测设备）供应商。要求设备精度在01005以上，有菲律宾或东南亚项目案例，可提供培训和本地维护。',
    descriptionEn: 'Manila EMS company seeks Chinese SMT placement and AOI equipment. Accuracy 01005 and above, Philippines/SEA references, training and local maintenance required.',
    type: 'demand',
    country: 'philippines',
    region: 'ph-manila',
    regionLabel: '马尼拉都会区',
    industry: '半导体/电子',
    cooperationType: 'supply',
    amount: '120',
    currency: 'USD',
    companyName: '马尼拉智造电子服务',
    companyNameEn: 'Manila Smart Electronics Services Inc.',
    contactEmail: 'equipment@mses.ph',
    publishedAt: '2026-03-10T08:00:00Z',
    expiresAt: '2026-06-10T08:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 印度 India (Tier 3) ═══════════════════
  {
    id: 'manual-in-001',
    title: '古吉拉特制药企业寻求中国原料药（API）供应商',
    titleEn: 'Gujarat Pharma Company Seeks China Active Pharmaceutical Ingredient (API) Supplier',
    description: '印度古吉拉特某大型制药企业，因供应链多元化需求，寻求中国原料药（API）供应商。要求有US FDA或EU GMP认证，已有印度进口记录或印度当地DMF注册优先。',
    descriptionEn: 'Gujarat pharmaceutical company seeking China API suppliers for supply chain diversification. US FDA or EU GMP certified, Indian import records or Indian DMF registration preferred.',
    type: 'demand',
    country: 'india',
    region: 'in-gujarat',
    regionLabel: '古吉拉特',
    industry: '医疗器械',
    cooperationType: 'supply',
    amount: '500',
    currency: 'USD',
    companyName: '古吉拉特蓝星制药',
    companyNameEn: 'Gujarat BlueStar Pharmaceuticals Ltd.',
    contactEmail: 'api@bluestarpharma.in',
    publishedAt: '2026-03-25T08:00:00Z',
    expiresAt: '2026-06-25T08:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-in-002',
    title: '马哈拉施特拉纺织企业寻求中国织机和染料助剂供应商',
    titleEn: 'Maharashtra Textile Company Seeks China Looms and Dye Chemicals Supplier',
    description: '印度马哈拉施特拉某纺织企业，扩张牛仔布产能，寻求中国剑杆织机/喷气织机和染料助剂供应商。要求设备可靠，有印度纺织企业合作记录，染料符合印度BIS标准。',
    descriptionEn: 'Maharashtra textile company expanding denim capacity seeks China rapier/air-jet looms and dye chemicals. Reliable equipment, India textile references, BIS-compliant dyes required.',
    type: 'demand',
    country: 'india',
    region: 'in-maharashtra',
    regionLabel: '马哈拉施特拉',
    industry: '纺织服装',
    cooperationType: 'supply',
    amount: '250',
    currency: 'USD',
    companyName: '马哈拉施特拉纺织工业',
    companyNameEn: 'Maharashtra Textile Industries Ltd.',
    contactEmail: 'machinery@mtitextile.in',
    publishedAt: '2026-03-20T08:00:00Z',
    expiresAt: '2026-06-20T08:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 巴基斯坦 Pakistan (Tier 3) ═══════════════════
  {
    id: 'manual-pk-001',
    title: '卡拉奇医药进口商寻求中国制剂设备合资合作',
    titleEn: 'Karachi Pharma Importer Seeks China Formulation Equipment Joint Venture',
    description: '巴基斯坦卡拉奇某医药进口商，计划在巴基斯坦建立口服固体制剂（片剂、胶囊）生产线，寻求中国制药设备商合资合作。要求设备符合PIC/S标准，有巴基斯坦或南亚项目案例优先。',
    descriptionEn: 'Karachi pharma importer planning oral solid dosage (tablet, capsule) production line in Pakistan seeks JV with Chinese pharma equipment maker. PIC/S compliant equipment, Pakistan/South Asia references preferred.',
    type: 'investment',
    country: 'pakistan',
    region: 'pk-karachi',
    regionLabel: '卡拉奇',
    industry: '医疗器械',
    cooperationType: 'joint-venture',
    amount: '200',
    currency: 'USD',
    companyName: '巴基斯坦阿尔劳医药',
    companyNameEn: 'Al-Rao Pharmaceuticals Pakistan',
    contactEmail: 'jv@alraopharma.pk',
    publishedAt: '2026-03-15T08:00:00Z',
    expiresAt: '2026-06-15T08:00:00Z',
    status: 'active',
    isPremium: true,
  },

  // ═══════════════════ 柬埔寨 Cambodia (Tier 3) ═══════════════════
  {
    id: 'manual-kh-001',
    title: '金边制衣企业寻求中国智能缝纫设备和MES系统供应商',
    titleEn: 'Phnom Penh Garment Factory Seeks China Smart Sewing Equipment & MES Supplier',
    description: '柬埔寨金边某成衣制造企业，计划升级自动化产线，寻求中国智能缝纫机（带激光裁剪）和MES制造执行系统供应商。要求设备耐用、适合东南亚气候，有柬埔寨服装工厂案例优先。',
    descriptionEn: 'Phnom Penh garment factory upgrading automation lines seeks China smart sewing machines (with laser cutting) and MES system suppliers. Durable equipment suitable for Southeast Asian climate, Cambodia garment factory references preferred.',
    type: 'demand',
    country: 'cambodia',
    region: 'kh-phnom-penh',
    regionLabel: '金边',
    industry: '纺织服装',
    cooperationType: 'supply',
    amount: '80',
    currency: 'USD',
    companyName: '金边制衣进出口公司',
    companyNameEn: 'Phnom Penh Garment Import Export Co.',
    contactEmail: 'factory@ppgarment.kh',
    publishedAt: '2026-03-10T08:00:00Z',
    expiresAt: '2026-06-10T08:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 缅甸 Myanmar (Tier 3) ═══════════════════
  {
    id: 'manual-mm-001',
    title: '仰光矿业公司寻求中国选矿设备和工艺技术合作',
    titleEn: 'Yangon Mining Company Seeks China Mineral Processing Equipment & Technical Cooperation',
    description: '缅甸仰光某有色金属矿业公司，计划升级金矿和铜矿选矿设备，寻求中国选矿设备供应商和技术许可合作。要求提供完整的选矿工艺方案，有东南亚矿业项目案例。',
    descriptionEn: 'Yangon non-ferrous metal mining company upgrading gold and copper mineral processing seeks Chinese equipment supplier and technical licensing partnership. Complete processing solution, Southeast Asia mining references required.',
    type: 'cooperation',
    country: 'myanmar',
    region: 'mm-yangon',
    regionLabel: '仰光',
    industry: '钢铁/金属',
    cooperationType: 'technology',
    amount: '150',
    currency: 'USD',
    companyName: '仰光矿业发展',
    companyNameEn: 'Yangon Mining Development Co.',
    contactEmail: 'tech@ymdmining.mm',
    publishedAt: '2026-03-05T08:00:00Z',
    expiresAt: '2026-06-05T08:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 老挝 Laos (Tier 3) ═══════════════════
  {
    id: 'manual-la-001',
    title: '万象农业公司寻求中国有机茶叶种植和加工设备出口合作',
    titleEn: 'Vientiane Agriculture Company Seeks China Organic Tea Planting & Processing Equipment Export',
    description: '老挝万象某农业公司，计划开发有机茶叶种植和深加工项目，寻求中国茶叶种植设备（灌溉、施肥系统）和制茶设备供应商。要求设备有有机认证支持，提供种植技术培训。',
    descriptionEn: 'Vientiane agriculture company planning organic tea cultivation and deep processing project seeks China tea planting equipment (irrigation, fertilization) and tea processing equipment. Organic certification support, planting technology training required.',
    type: 'demand',
    country: 'laos',
    region: 'la-vientiane',
    regionLabel: '万象经济特区',
    industry: '食品农业',
    cooperationType: 'supply',
    amount: '60',
    currency: 'USD',
    companyName: '老挝绿色农业发展',
    companyNameEn: 'Laos Green Agriculture Development Co.',
    contactEmail: 'agri@lgad.la',
    publishedAt: '2026-03-08T08:00:00Z',
    expiresAt: '2026-06-08T08:00:00Z',
    status: 'active',
    isPremium: false,
  },

  // ═══════════════════ 中国→亚洲出口 Supply from China ═══════════════════
  {
    id: 'manual-cn-001',
    title: '深圳储能系统制造商寻求日本家用储能代理合作',
    titleEn: 'Shenzhen ESS Manufacturer Seeks Japan Home Energy Storage Agency',
    description: '深圳某储能系统制造商，产品已通过日本SII认证，寻求日本市场家用储能（BESS）代理合作伙伴。要求有日本分布式能源或家居产品分销网络，有日本团队支持售后服务。',
    descriptionEn: 'Shenzhen ESS manufacturer with SII-certified products seeks Japan home energy storage (BESS) agency partner. Japanese distributed energy or home products distribution network, Japanese after-sales support required.',
    type: 'supply',
    country: 'japan',
    region: 'jp-tokyo',
    regionLabel: '东京首都圈',
    industry: '能源电力',
    cooperationType: 'agency',
    amount: '200',
    currency: 'USD',
    companyName: '深圳华储科技',
    companyNameEn: 'Shenzhen Huachu Energy Technology Co.',
    contactEmail: 'japan@huachu-tech.cn',
    publishedAt: '2026-03-20T08:00:00Z',
    expiresAt: '2026-06-20T08:00:00Z',
    status: 'active',
    isPremium: true,
  },
  {
    id: 'manual-cn-002',
    title: '苏州工业机器人制造商寻求东南亚经销商合作',
    titleEn: 'Suzhou Industrial Robot Manufacturer Seeks Southeast Asia Distributors',
    description: '苏州某工业机器人制造商，产品已出口欧洲并获得CE认证，现寻求越南、泰国、印尼的工业机器人经销商合作。要求有当地制造业客户资源，可提供本地化培训和技术支持。',
    descriptionEn: 'Suzhou industrial robot manufacturer with CE-certified products seeks Vietnam, Thailand, and Indonesia distributors. Local manufacturing customer resources, localized training and technical support required.',
    type: 'supply',
    country: 'singapore',
    region: 'sg-central',
    regionLabel: '中城区',
    industry: '工业自动化',
    cooperationType: 'distribution',
    amount: '300',
    currency: 'USD',
    companyName: '苏州智造机器人',
    companyNameEn: 'Suzhou Zhizao Robotics Co., Ltd.',
    contactEmail: 'sea@zhizaorobot.cn',
    publishedAt: '2026-03-25T08:00:00Z',
    expiresAt: '2026-06-25T08:00:00Z',
    status: 'active',
    isPremium: true,
  },
];

// ── Main ──────────────────────────────────────────────────────────────────
function main() {
  let data = [];
  if (fs.existsSync(DATA_FILE)) {
    try {
      data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
    } catch (e) {
      console.error('Failed to parse JSON:', e.message);
      process.exit(1);
    }
  }

  const countBefore = data.length;

  // 1. Remove noise entries
  const clean = data.filter(entry => !isNoise(entry));
  const removed = countBefore - clean.length;
  console.log(`Removed ${removed} noise entries (kept ${clean.length} good entries)`);

  // 2. Get existing manual entry IDs (don't duplicate)
  const existingIds = new Set(clean.map(e => e.id));

  // 3. Add new manual entries (skip if already exists)
  let added = 0;
  for (const entry of MANUAL_ENTRIES) {
    if (!existingIds.has(entry.id)) {
      clean.unshift(entry); // add to front
      added++;
    }
  }
  console.log(`Added ${added} new high-quality manual entries`);

  // 4. Sort by publishedAt descending, cap at 500
  clean.sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));
  const final = clean.slice(0, 500);

  // 5. Write back
  fs.writeFileSync(DATA_FILE, JSON.stringify(final, null, 2), { encoding: 'utf8' });
  console.log(`Final count: ${final.length} entries`);
  console.log(`Breakdown: manual=${final.filter(e => !e.dataSource).length}, auto=${final.filter(e => e.dataSource).length}`);

  // 6. Country stats
  const byCountry = {};
  final.forEach(e => { byCountry[e.country] = (byCountry[e.country] || 0) + 1; });
  console.log('\nBy country:');
  Object.entries(byCountry).sort((a, b) => b[1] - a[1]).forEach(([c, n]) => console.log(`  ${c}: ${n}`));
}

main();
